UE-363: fixing up for the underline on the caret
SU-SWS/vpue_undergrad_subtheme pull request #32
Opened 2021-10-06 19:23 UTC by jenbreese

# READY FOR REVIEW

# Summary
- Create a focus line when tabbing or clicking to a secondary navigation. 
- On the home page there is now a heavy white line above the caret
- Other pages kept the same focus since it did have one. 
- No changes to the responsive views.
- Made the border line between the link and caret a white from the grey.
- Remove the underline on the caret for sub menus.
- replaces this pull request: https://github.com/SU-SWS/vpue_undergrad_subtheme/pull/28

# Review By (Date)
- 10/10

# Criticality
- Normal
- Accessibility

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Turn on drop down menu
4. add content in the drop downs
3. Navigate to the homepage 
4. Verify when using the keyboard, you can see the focus change on the Caret.
5. Verify that the nested menus have the default colors and behaviors. 

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- [UE-363](https://stanfordits.atlassian.net/browse/UE-363)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-10-07 18:00 UTC, jdwjdwjdw requested changes

2021-10-07 18:00 UTC, jdwjdwjdw commented on src/scss/components/main-nav/_main-nav.scss
> +            border: 0;
It looks like this may be too broad, since it also removes the desired white line above the caret for me. Additionally, since you only added the white caret underline to the homepage and not the whole site, I think we should only remove the black underline on the homepage instead of every page.

2021-10-07 20:59 UTC, jenbreese commented on src/scss/components/main-nav/_main-nav.scss
> +            border: 0;
@jdwjdwjdw I did it but I think we might want to look at this more carefully with our client. without the underline, there is no focus state on that down caret which is an accessibility thing.

2021-10-12 23:20 UTC, jdwjdwjdw approved these changes
GTG. Thanks for the great collaboration and quick fixups!

2021-10-12 23:21 UTC, merged